#!/usr/bin/env python3
"""OfficeLM Setup Wizard.

Interactive CLI that generates a complete, production-ready `.env` file for
OfficeLM. Run once before `docker compose up`.

Usage:
    python setup.py              # Interactive wizard
    python setup.py --non-interactive --provider local --model llama3.1:8b
"""
import os
import secrets
import sys
from pathlib import Path
from typing import Optional

try:
    import typer
    from rich.console import Console
    from rich.panel import Panel
    from rich.prompt import Confirm, Prompt
except ImportError:
    print("Dependencies missing. Installing typer and rich...")
    os.system(f"{sys.executable} -m pip install typer rich")
    import typer
    from rich.console import Console
    from rich.panel import Panel
    from rich.prompt import Confirm, Prompt

app = typer.Typer(help="OfficeLM Interactive Setup Wizard")
console = Console()

ENV_PATH = Path(__file__).parent / ".env"

SUPPORTED_CHAT_MODELS = {
    "ollama": [
        ("llama3.1:8b", "Meta Llama 3.1 8B — Best all-rounder for 8GB+ RAM"),
        ("mistral:7b", "Mistral 7B — Fast, lightweight, great logic"),
        ("phi3:mini", "Microsoft Phi-3 Mini 3.8B — Extremely fast, low RAM"),
    ],
    "openai": [
        ("gpt-4o", "GPT-4o — Flagship multimodal model"),
        ("gpt-4o-mini", "GPT-4o Mini — Fast, affordable default"),
        ("o3-mini", "o3-mini — Advanced reasoning model"),
    ],
    "gemini": [
        ("gemini-2.5-flash", "Gemini 2.5 Flash — Fast & powerful default"),
        ("gemini-2.5-pro", "Gemini 2.5 Pro — Complex reasoning & long context"),
        ("gemini-2.0-flash", "Gemini 2.0 Flash — Proven stable generation"),
    ],
}

DEFAULT_EMBEDDINGS = {
    "ollama": "nomic-embed-text:latest",
    "openai": "text-embedding-3-small",
    "gemini": "text-embedding-004",
}


def generate_env(
    provider: str,
    llm_model: str,
    embedding_model: str,
    api_key: Optional[str] = None,
    enable_gpu: bool = False,
    admin_email: str = "admin@officelm.local",
    admin_password: Optional[str] = None,
) -> str:
    secret_key = secrets.token_hex(64)
    jwt_secret = secrets.token_hex(64)
    refresh_secret = secrets.token_hex(64)
    postgres_pass = secrets.token_hex(16)
    redis_pass = secrets.token_hex(16)
    minio_root_pass = secrets.token_hex(16)
    admin_pass = admin_password or secrets.token_hex(12)

    env_content = f"""# ============================================================
# OfficeLM System Configuration
# Auto-generated by setup.py
# ============================================================

# CORE APPLICATION
APP_NAME="OfficeLM System"
ENVIRONMENT=prod
DEBUG=false
SECRET_KEY={secret_key}
FRONTEND_URL=http://localhost:3000

# INITIAL SUPERADMIN ACCOUNT
INITIAL_ADMIN_EMAIL={admin_email}
INITIAL_ADMIN_PASSWORD={admin_pass}

# SECURITY & AUTHENTICATION
JWT_SECRET_KEY={jwt_secret}
JWT_REFRESH_SECRET_KEY={refresh_secret}
JWT_ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=30
REFRESH_TOKEN_EXPIRE_DAYS=7

# LLM PROVIDER & MODELS
LLM_PROVIDER={provider}
LLM_MODEL={llm_model}
EMBEDDING_MODEL={embedding_model}
OLLAMA_BASE_URL=http://ollama:11434
OPENAI_API_KEY={api_key if provider == 'openai' else ''}
OPENAI_BASE_URL=https://api.openai.com/v1
GEMINI_API_KEY={api_key if provider == 'gemini' else ''}
ENABLE_GPU={"true" if enable_gpu else "false"}

# DATABASE (PostgreSQL)
POSTGRES_USER=officelm
POSTGRES_PASSWORD={postgres_pass}
POSTGRES_DB=officelm_db
POSTGRES_HOST=postgres
POSTGRES_PORT=5432
DATABASE_URL=postgresql://officelm:{postgres_pass}@postgres:5432/officelm_db

# CACHE & MESSAGING (Redis)
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD={redis_pass}
REDIS_URL=redis://:{redis_pass}@redis:6379/0

# OBJECT STORAGE (MinIO / S3)
MINIO_ENDPOINT=minio:9000
MINIO_ROOT_USER=minioadmin
MINIO_ROOT_PASSWORD={minio_root_pass}
MINIO_BUCKET_NAME=officelm-files
MINIO_SECURE=false

# LOGGING
LOG_LEVEL=INFO
"""
    return env_content


@app.command()
def main(
    non_interactive: bool = typer.Option(False, "--non-interactive", help="Run without prompts"),
    provider: str = typer.Option("ollama", "--provider", help="LLM provider: ollama | openai | gemini"),
    model: Optional[str] = typer.Option(None, "--model", help="LLM model name"),
    api_key: Optional[str] = typer.Option(None, "--api-key", help="API key for remote providers"),
    enable_gpu: bool = typer.Option(False, "--gpu", help="Enable NVIDIA GPU acceleration in Docker Compose"),
):
    console.print(Panel.fit("[bold blue]Welcome to OfficeLM Setup Wizard[/bold blue]", border_style="blue"))

    if non_interactive:
        selected_provider = provider.lower()
        selected_model = model or SUPPORTED_CHAT_MODELS[selected_provider][0][0]
        embedding_model = DEFAULT_EMBEDDINGS[selected_provider]
        env_text = generate_env(
            provider=selected_provider,
            llm_model=selected_model,
            embedding_model=embedding_model,
            api_key=api_key,
            enable_gpu=enable_gpu,
        )
        ENV_PATH.write_text(env_text, encoding="utf-8")
        console.print(f"[bold green]Config generated at {ENV_PATH}[/bold green]")
        return

    # Step 1: Provider
    console.print("\n[bold]Step 1/4: Choose AI Deployment Mode[/bold]")
    console.print("  [1] Local (Ollama) - 100% private, runs entirely on your hardware")
    console.print("  [2] OpenAI Remote  - Requires API Key (GPT-4o, GPT-4o-mini, o3-mini)")
    console.print("  [3] Google Gemini  - Requires API Key (Gemini 2.5 Flash, 2.5 Pro)")

    choice = Prompt.ask("Select mode", choices=["1", "2", "3"], default="1")
    provider_map = {"1": "ollama", "2": "openai", "3": "gemini"}
    selected_provider = provider_map[choice]

    # Step 2: Model selection
    console.print(f"\n[bold]Step 2/4: Choose Model for {selected_provider.upper()}[/bold]")
    models = SUPPORTED_CHAT_MODELS[selected_provider]
    for idx, (m_id, m_desc) in enumerate(models, 1):
        console.print(f"  [{idx}] {m_id} — {m_desc}")

    m_choice = Prompt.ask("Select model", choices=[str(i) for i in range(1, len(models) + 1)], default="1")
    selected_model = models[int(m_choice) - 1][0]
    embedding_model = DEFAULT_EMBEDDINGS[selected_provider]

    # Step 3: API Key or GPU
    selected_api_key = None
    gpu_flag = False
    if selected_provider in ("openai", "gemini"):
        selected_api_key = Prompt.ask(f"Enter your {selected_provider.upper()} API Key", password=True)
    else:
        gpu_flag = Confirm.ask("Do you have an NVIDIA GPU to accelerate local inference?", default=False)

    # Step 4: Initial Admin Credentials
    console.print("\n[bold]Step 4/4: Initial Admin Account[/bold]")
    admin_email = Prompt.ask("Admin Email", default="admin@officelm.local")
    admin_password = Prompt.ask("Admin Password (leave blank for random generated)", default="", password=True)
    if not admin_password:
        admin_password = secrets.token_hex(12)
        console.print(f"[yellow]Generated Admin Password: {admin_password}[/yellow]")

    # Generate .env
    env_text = generate_env(
        provider=selected_provider,
        llm_model=selected_model,
        embedding_model=embedding_model,
        api_key=selected_api_key,
        enable_gpu=gpu_flag,
        admin_email=admin_email,
        admin_password=admin_password,
    )
    ENV_PATH.write_text(env_text, encoding="utf-8")

    console.print(Panel.fit("[bold green]Setup Complete! .env file created.[/bold green]", border_style="green"))
    console.print("\nNext step: run `docker compose up -d` to launch OfficeLM.")


if __name__ == "__main__":
    app()
