"""created_models_for_chat_module

Revision ID: 40b75c1b3864
Revises: df8aad89947d
Create Date: 2026-09-14 19:12:07.978132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40b75c1b3864'
down_revision: Union[str, None] = 'df8aad89947d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Ensure the PostgreSQL 'chat' schema exists before creating tables
    op.execute("CREATE SCHEMA IF NOT EXISTS chat")

    # ### commands auto generated by Alembic - please adjust! ###
    # === ChatRoom Model ===
    op.create_table('chat_rooms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['auth.users.id'], name=op.f('fk_chat_rooms_creator_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_rooms')),
    schema='chat'
    )
    op.create_index(op.f('ix_chat_chat_rooms_creator_id'), 'chat_rooms', ['creator_id'], unique=False, schema='chat')
    op.create_index(op.f('ix_chat_chat_rooms_name'), 'chat_rooms', ['name'], unique=False, schema='chat')


    # === ChatMessage Model ===
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chat_room_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='chatmessagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_room_id'], ['chat.chat_rooms.id'], name=op.f('fk_chat_messages_chat_room_id_chat_rooms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['auth.users.id'], name=op.f('fk_chat_messages_sender_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages')),
    schema='chat'
    )
    op.create_index(op.f('ix_chat_chat_messages_chat_room_id'), 'chat_messages', ['chat_room_id'], unique=False, schema='chat')
    op.create_index(op.f('ix_chat_chat_messages_role'), 'chat_messages', ['role'], unique=False, schema='chat')
    op.create_index(op.f('ix_chat_chat_messages_sender_id'), 'chat_messages', ['sender_id'], unique=False, schema='chat')


    # === ChatRoomMembers Model ===
    op.create_table('chat_room_members',
    sa.Column('chat_room_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='chatmemberrole'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_room_id'], ['chat.chat_rooms.id'], name=op.f('fk_chat_room_members_chat_room_id_chat_rooms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['auth.users.id'], name=op.f('fk_chat_room_members_member_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_room_id', 'member_id', name=op.f('pk_chat_room_members')),
    schema='chat'
    )
    op.create_index(op.f('ix_chat_chat_room_members_role'), 'chat_room_members', ['role'], unique=False, schema='chat')


    # === FileJob Model ===
    op.create_table('file_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('file_type', sa.Enum('MD', 'DOCX', 'XLSX', 'PDF', name='filetype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='filejobstatus'), nullable=False),
    sa.Column('output_path', sa.String(length=512), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['chat.chat_messages.id'], name=op.f('fk_file_jobs_message_id_chat_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('fk_file_jobs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_file_jobs')),
    schema='chat'
    )
    op.create_index(op.f('ix_chat_file_jobs_file_type'), 'file_jobs', ['file_type'], unique=False, schema='chat')
    op.create_index(op.f('ix_chat_file_jobs_message_id'), 'file_jobs', ['message_id'], unique=False, schema='chat')
    op.create_index(op.f('ix_chat_file_jobs_status'), 'file_jobs', ['status'], unique=False, schema='chat')
    op.create_index(op.f('ix_chat_file_jobs_user_id'), 'file_jobs', ['user_id'], unique=False, schema='chat')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_file_jobs_user_id'), table_name='file_jobs', schema='chat')
    op.drop_index(op.f('ix_chat_file_jobs_status'), table_name='file_jobs', schema='chat')
    op.drop_index(op.f('ix_chat_file_jobs_message_id'), table_name='file_jobs', schema='chat')
    op.drop_index(op.f('ix_chat_file_jobs_file_type'), table_name='file_jobs', schema='chat')
    op.drop_table('file_jobs', schema='chat')
    op.drop_index(op.f('ix_chat_chat_room_members_role'), table_name='chat_room_members', schema='chat')
    op.drop_table('chat_room_members', schema='chat')
    op.drop_index(op.f('ix_chat_chat_messages_sender_id'), table_name='chat_messages', schema='chat')
    op.drop_index(op.f('ix_chat_chat_messages_role'), table_name='chat_messages', schema='chat')
    op.drop_index(op.f('ix_chat_chat_messages_chat_room_id'), table_name='chat_messages', schema='chat')
    op.drop_table('chat_messages', schema='chat')
    op.drop_index(op.f('ix_chat_chat_rooms_name'), table_name='chat_rooms', schema='chat')
    op.drop_index(op.f('ix_chat_chat_rooms_creator_id'), table_name='chat_rooms', schema='chat')
    op.drop_table('chat_rooms', schema='chat')
    # ### end Alembic commands ###
