"""table_users_added_failed_login_attempt_time_&_banned_until_time

Revision ID: 59c7a358bd44
Revises: 6502f63d255e
Create Date: 2026-08-14 18:52:00.155721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59c7a358bd44'
down_revision: Union[str, None] = '6502f63d255e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('failed_login_attempt_time', sa.DateTime(timezone=True), nullable=True), schema='auth')
    op.add_column('users', sa.Column('banned_until_time', sa.DateTime(timezone=True), nullable=True), schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'banned_until_time', schema='auth')
    op.drop_column('users', 'failed_login_attempt_time', schema='auth')
    # ### end Alembic commands ###
