"""user_table_added_failed_login_attempt_cnt_small_int_value

Revision ID: 6502f63d255e
Revises: 4bcbf8faef24
Create Date: 2026-08-14 18:33:07.468918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6502f63d255e'
down_revision: Union[str, None] = '4bcbf8faef24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('users', sa.Column('failed_login_attempt_cnt', sa.SmallInteger(), nullable=False), schema='auth')
    
    # Add the column as nullable first so existing rows can accept NULL temporarily
    op.add_column('users', sa.Column('failed_login_attempt_cnt', sa.SmallInteger(), nullable=True), schema="auth")
    
    # Update all existing rows to have 0 instead of NULL
    op.execute("UPDATE auth.users SET failed_login_attempt_cnt = 0 WHERE failed_login_attempt_cnt IS NULL")
    
    # Now alter the column to strictly enforce NOT NULL
    op.alter_column('users', 'failed_login_attempt_cnt', nullable=False, schema="auth")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'failed_login_attempt_cnt', schema='auth')
    # ### end Alembic commands ###
