"""remove_obsolete_auth.users_columns

Revision ID: df8aad89947d
Revises: 7f8e9d0c1b2a
Create Date: 2026-08-17 20:35:37.056331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df8aad89947d'
down_revision: Union[str, None] = '7f8e9d0c1b2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'failed_login_attempt_time', schema='auth')
    op.drop_column('users', 'failed_login_attempt_cnt', schema='auth')
    op.drop_index(op.f('ix_auth_sessions_refresh_token_hash'), table_name='sessions', schema='session')
    op.drop_index(op.f('ix_auth_sessions_user_active'), table_name='sessions', schema='session')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='sessions', schema='session')
    op.create_index(op.f('ix_session_sessions_refresh_token_hash'), 'sessions', ['refresh_token_hash'], unique=True, schema='session')
    op.create_index('ix_session_sessions_user_active', 'sessions', ['user_id', 'is_active'], unique=False, schema='session')
    op.create_index(op.f('ix_session_sessions_user_id'), 'sessions', ['user_id'], unique=False, schema='session')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_sessions_user_id'), table_name='sessions', schema='session')
    op.drop_index('ix_session_sessions_user_active', table_name='sessions', schema='session')
    op.drop_index(op.f('ix_session_sessions_refresh_token_hash'), table_name='sessions', schema='session')
    op.create_index(op.f('ix_auth_sessions_user_id'), 'sessions', ['user_id'], unique=False, schema='session')
    op.create_index(op.f('ix_auth_sessions_user_active'), 'sessions', ['user_id', 'is_active'], unique=False, schema='session')
    op.create_index(op.f('ix_auth_sessions_refresh_token_hash'), 'sessions', ['refresh_token_hash'], unique=True, schema='session')
    op.add_column('users', sa.Column('failed_login_attempt_cnt', sa.SMALLINT(), autoincrement=False, nullable=False), schema='auth')
    op.add_column('users', sa.Column('failed_login_attempt_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True), schema='auth')
    # ### end Alembic commands ###
